# **Importing Libraries**

In [25]:
import pandas as pd
import plotly.express as px

# **Exploring Data**

In [26]:
data = pd.read_csv('ai_job_dataset.csv')

In [27]:
data.head()

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
0,AI00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,1076,5.9,Smart Analytics
1,AI00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,1268,5.2,TechCorp Inc
2,AI00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,1974,9.4,Autonomous Tech
3,AI00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,1345,8.6,Future Systems
4,AI00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,1989,6.6,Advanced Robotics

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   job_id                  15000 non-null  object
 1   job_title               15000 non-null  object
 2   salary_usd              15000 non-null  int64
 3   salary_currency         15000 non-null  object
 4   experience_level        15000 non-null  object
 5   employment_type         15000 non-null  object
 6   company_location        15000 non-null  object
 7   company_size            15000 non-null  object
 8   employee_residence      15000 non-null  object
 9   remote_ratio            15000 non-null  int64
 10  required_skills         15000 non-null  object
 11  education_required      15000 non-null  object
 12  years_experience        15000 non-null  int64
 13  industry                15000 non-null  object
 14  posting_date            15000 non-null  object
 15  application_deadline    15000 non-null  object
 16  job_description_length  15000 non-null  int64
 17  benefits_score          15000 non-null  float64
 18  company_name            15000 non-null  object
dtypes: float64(1), int64(4), object(14)
memory usage: 2.2+ MB

In [29]:
data.describe()

,salary_usd,remote_ratio,years_experience,job_description_length,benefits_score
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,115348.965133,49.483333,6.253200,1503.314733,7.504273
std,60260.940438,40.812712,5.545768,576.127083,1.450870
min,32519.000000,0.000000,0.000000,500.000000,5.000000
25%,70179.750000,0.000000,2.000000,1003.750000,6.200000
50%,99705.000000,50.000000,5.000000,1512.000000,7.500000
75%,146408.500000,100.000000,10.000000,2000.000000,8.800000
max,399095.000000,100.000000,19.000000,2499.000000,10.000000

In [30]:
data.isna().sum()

job_id                    0
job_title                 0
salary_usd                0
salary_currency           0
experience_level          0
employment_type           0
company_location          0
company_size              0
employee_residence        0
remote_ratio              0
required_skills           0
education_required        0
years_experience          0
industry                  0
posting_date              0
application_deadline      0
job_description_length    0
benefits_score            0
company_name              0
dtype: int64

In [31]:
data.duplicated().sum()

np.int64(0)

# **Cleaning**

In [32]:
df = data.copy()
df.head()

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
0,AI00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,1076,5.9,Smart Analytics
1,AI00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,1268,5.2,TechCorp Inc
2,AI00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,1974,9.4,Autonomous Tech
3,AI00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,1345,8.6,Future Systems
4,AI00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,1989,6.6,Advanced Robotics

In [33]:
# drop unnecessary columns
df.drop(['job_id', 'salary_currency', 'employee_residence', 'job_description_length', 'benefits_score'], axis=1, inplace=True)

In [34]:
df.head()

,job_title,salary_usd,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,company_name
0,AI Research Scientist,90376,SE,CT,China,M,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,Smart Analytics
1,AI Software Engineer,61895,EN,CT,Canada,M,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,TechCorp Inc
2,AI Specialist,152626,MI,FL,Switzerland,L,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,Autonomous Tech
3,NLP Engineer,80215,SE,FL,India,M,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,Future Systems
4,AI Consultant,54624,EN,PT,France,S,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,Advanced Robotics

In [35]:
# rename columns 
df.rename(columns={'salary_usd':'annual_salary'}, inplace=True)

In [36]:
df.head()

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,company_name
0,AI Research Scientist,90376,SE,CT,China,M,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,Smart Analytics
1,AI Software Engineer,61895,EN,CT,Canada,M,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,TechCorp Inc
2,AI Specialist,152626,MI,FL,Switzerland,L,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,Autonomous Tech
3,NLP Engineer,80215,SE,FL,India,M,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,Future Systems
4,AI Consultant,54624,EN,PT,France,S,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,Advanced Robotics

## Feature Engineering

In [37]:
df['monthly_salary'] = df['annual_salary'] / 12
df.head()

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,company_name,monthly_salary
0,AI Research Scientist,90376,SE,CT,China,M,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,Smart Analytics,7531.333333
1,AI Software Engineer,61895,EN,CT,Canada,M,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,TechCorp Inc,5157.916667
2,AI Specialist,152626,MI,FL,Switzerland,L,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,Autonomous Tech,12718.833333
3,NLP Engineer,80215,SE,FL,India,M,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,Future Systems,6684.583333
4,AI Consultant,54624,EN,PT,France,S,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,Advanced Robotics,4552.000000

In [38]:
df.experience_level = df.experience_level.apply(lambda x: 'Entry' if x == 'EN' else 'Mid' if x == 'MI' else 'Senior' if x == 'SE' else 'Executive')
df.experience_level

0           Senior
1            Entry
2              Mid
3           Senior
4            Entry
           ...
14995        Entry
14996        Entry
14997    Executive
14998        Entry
14999          Mid
Name: experience_level, Length: 15000, dtype: object

In [39]:
df.employment_type = df.employment_type.apply(lambda x: 'Full Time' if x == 'FT' else 'Part Time' if x == 'PT' else 'Contract' if x == 'CT' else 'Freelance')
df.employment_type

0         Contract
1         Contract
2        Freelance
3        Freelance
4        Part Time
           ...
14995    Freelance
14996     Contract
14997     Contract
14998    Full Time
14999    Part Time
Name: employment_type, Length: 15000, dtype: object

In [40]:
df.company_size = df.company_size.apply(lambda x: 'Small <50' if x == 'S' else 'Medium 50-250' if x == 'M' else 'Large >250')
df.company_size

0        Medium 50-250
1        Medium 50-250
2           Large >250
3        Medium 50-250
4            Small <50
             ...
14995        Small <50
14996    Medium 50-250
14997       Large >250
14998    Medium 50-250
14999        Small <50
Name: company_size, Length: 15000, dtype: object

In [41]:
df['remote_state'] = df['remote_ratio'].apply(lambda x: 'No remote' if x == 0 else 'Hybrid' if x == 50 else 'Fully remote')
df.head()

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,company_name,monthly_salary,remote_state
0,AI Research Scientist,90376,Senior,Contract,China,Medium 50-250,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,Smart Analytics,7531.333333,Hybrid
1,AI Software Engineer,61895,Entry,Contract,Canada,Medium 50-250,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,TechCorp Inc,5157.916667,Fully remote
2,AI Specialist,152626,Mid,Freelance,Switzerland,Large >250,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,Autonomous Tech,12718.833333,No remote
3,NLP Engineer,80215,Senior,Freelance,India,Medium 50-250,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,Future Systems,6684.583333,Hybrid
4,AI Consultant,54624,Entry,Part Time,France,Small <50,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,Advanced Robotics,4552.000000,Fully remote

In [42]:
# extract each skill from the required_skills column
skill_set = set()
for item in df.required_skills.apply(lambda x: x.split(', ')):
    for skill in item:
        skill_set.add(skill)

In [43]:
skill_set

{'AWS',
 'Azure',
 'Computer Vision',
 'Data Visualization',
 'Deep Learning',
 'Docker',
 'GCP',
 'Git',
 'Hadoop',
 'Java',
 'Kubernetes',
 'Linux',
 'MLOps',
 'Mathematics',
 'NLP',
 'PyTorch',
 'Python',
 'R',
 'SQL',
 'Scala',
 'Spark',
 'Statistics',
 'Tableau',
 'TensorFlow'}

In [44]:
# create a new column for each skill
for skill in skill_set:
    df[skill] = df.required_skills.apply(lambda x: 1 if skill in x else 0)

In [45]:
# drop unnecessary columns
df.drop(['remote_ratio', 'required_skills'], axis=1, inplace=True)

## Saving Clean Data

In [46]:
df.to_csv("ai_job_cleaned.csv", index=False)